// Code generated by https://github.com/GoComply/metaschema; DO NOT EDIT.
// Multiplexers are indirect models needed for serialization/deserialization
// as json and xml files differ materially in their structure.
package plan_of_action_and_milestones

type ComponentMultiplexer = []Component
type InventoryItemMultiplexer = []InventoryItem
