builds:
  - binary: gocomply_oscalkit
    main: ./cli/gocomply_oscalkit/main.go
    ldflags: -s -w -X github.com/gocomply/oscalkit/cli/version.Version={{.Version}} -X github.com/gocomply/oscalkit/cli/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

brew:
  name: oscalkit
  github:
    owner: gocomply
    name: homebrew-oscalkit
  commit_author:
    name: Šimon Lukašík
    email: isimluk@fedoraproject.org
  homepage: https://github.com/gocomply/oscalkit
  dependencies:
    - libxml2
