// Code generated by https://github.com/GoComply/metaschema; DO NOT EDIT.
// Multiplexers are indirect models needed for serialization/deserialization
// as json and xml files differ materially in their structure.
package validation_common_root

type IncorporatesComponentMultiplexer = []IncorporatesComponent
type OnlyStatementMultiplexer = []OnlyStatement
type ResponsibleRoleMultiplexer = []ResponsibleRole
type SetParameterMultiplexer = []SetParameter
