// Code generated by https://github.com/GoComply/metaschema; DO NOT EDIT.
// Multiplexers are indirect models needed for serialization/deserialization
// as json and xml files differ materially in their structure.
package system_security_plan

type ComponentMultiplexer = []Component
type ResponsibleRoleMultiplexer = []ResponsibleRole
type InventoryItemMultiplexer = []InventoryItem
type ByComponentMultiplexer = []ByComponent
type SetParameterMultiplexer = []SetParameter
type ResponsiblePartyMultiplexer = []ResponsibleParty
type DiagramMultiplexer = []Diagram
type UserMultiplexer = []User
type StatementMultiplexer = []Statement
type ImplementedComponentMultiplexer = []ImplementedComponent
