// Code generated by https://github.com/GoComply/metaschema; DO NOT EDIT.
// Multiplexers are indirect models needed for serialization/deserialization
// as json and xml files differ materially in their structure.
package component_definition

type IncorporatesComponentMultiplexer = []IncorporatesComponent
type ResponsibleRoleMultiplexer = []ResponsibleRole
type SetParameterMultiplexer = []SetParameter
type StatementMultiplexer = []Statement
type ComponentMultiplexer = []Component
type CapabilityMultiplexer = []Capability
type ResponsiblePartyMultiplexer = []ResponsibleParty
