// Code generated by https://github.com/GoComply/metaschema; DO NOT EDIT.
// Multiplexers are indirect models needed for serialization/deserialization
// as json and xml files differ materially in their structure.
package assessment_plan

type ComponentMultiplexer = []Component
type InventoryItemMultiplexer = []InventoryItem
type UserMultiplexer = []User
